redis:
    host: localhost
    port: 6379
    max-clients: 2


facebook:
    app-id: 1518760638222190
    secret-key: aab478fd8d3ee8759816617afd27a295
    verify-token: chatclub-webinar
    page:
        id: 176864459596254
        access-token: EAAVlTgRXD24BAEaH4UeeTkmZCVu9AxgQVXiHrhTZA1BbZCeBRLiBo3HcpjOuieYGf4wm9JtzkEz0IEFr0cqaoQCC1G05eYszUSQoIYaO6SdpeuVBxXCYgMSHvZC7VbbVJQoI729U3yiEQaSTZAPNohlBO3GLijWggOPVH4fJVMhTZAaUORwbDF